export const charityList = [
    {
        name: "The Developers",
        link: "https://daniellitt.wixsite.com/website",
        description: "Help us maintain this website.",
        logoURL: "https://static.thenounproject.com/png/962492-200.png",
        totalDonated: 0,
    },
    {
        name: "Doctors Without Borders",
        link: "https://www.doctorswithoutborders.org/",
        description: "Médecins Sans Frontières, sometimes rendered in English as Doctors Without Borders, is an international humanitarian medical non-governmental organisation of French origin best known for its projects in conflict zones and in countries affected by endemic diseases.",
        logoURL: "https://www.doctorswithoutborders.org/themes/custom/msf/screenshot.png",
        totalDonated: 0,
    },
    {
        name: "American Red Cross",
        link: "https://www.redcross.org/",
        description: "The American Red Cross, also known as The American National Red Cross, is a humanitarian organization that provides emergency assistance, disaster relief, and disaster preparedness education in the United States.",
        logoURL: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/American_Red_Cross_logo.svg/1024px-American_Red_Cross_logo.svg.png",
        totalDonated: 0,
    },
    {
        name: "The Nature Conservancy",
        link: "https://www.nature.org/en-us/",
        description: "The Nature Conservancy is a charitable environmental organization, headquartered in Arlington, Virginia, United States. Founded in 1951, The Nature Conservancy has over one million members, and has protected more than 119,000,000 acres of land and thousands of miles of rivers worldwide.",
        logoURL: "https://images.squarespace-cdn.com/content/v1/54aed6cee4b060149458baf1/1519052355044-4IGCQVGAQSHXUBRJO2B6/ke17ZwdGBToddI8pDm48kCNtot3vrE2sNYlaQ6cY7RFZw-zPPgdn4jUwVcJE1ZvWQUxwkmyExglNqGp0IvTJZamWLI2zvYWH8K3-s_4yszcp2ryTI0HqTOaaUohrI8PI4qTO-rVw-7KD42KpuL3Zq2b6qV70rcNQCKKPwoodJXs/TNC-Partner-Logo-Website.png",
        totalDonated: 0,
    },
    {
        name: "ASPCA",
        link: "https://www.aspca.org/",
        description: "The American Society for the Prevention of Cruelty to Animals is a non-profit organization dedicated to preventing cruelty to animals. Based in New York City since its inception in 1866, the organization's mission is \"to provide effective means for the prevention of cruelty to animals throughout the United States.\"",
        logoURL: "https://indyweek.com/downloads/14763/download/aspca-logo-square.png?cb=f4c957f9e7b68350f76f7ccc0e4b2b20",
        totalDonated: 0,
    },
    {
        name: "Disabled American Veterans",
        link: "https://www.dav.org/",
        description: "The Disabled American Veterans is an organization created by the United States Congress for disabled military veterans of the United States Armed Forces that helps them and their families through various means. It currently has over 1 million members.",
        logoURL: "https://images.squarespace-cdn.com/content/v1/5b509f1f8f5130e4eec53c8f/1548066080052-K57IRG47QKOY2CUDYW0S/ke17ZwdGBToddI8pDm48kP_cbzRYuUSc2ud9TTOyZ0dZw-zPPgdn4jUwVcJE1ZvWEtT5uBSRWt4vQZAgTJucoTqqXjS3CfNDSuuf31e0tVHCSxKkJfJvvC3BMJfuvOdVs7BHa07DMsenDOeuOaKOaKQvevUbj177dmcMs1F0H-0/SCP-Client-Logos_0011_DAV.png",
        totalDonated: 0,
    },
    {
        name: "Save The Children",
        link: "https://www.savethechildren.org/",
        description: "The Save the Children Fund, commonly known as Save the Children was established in the United Kingdom in 1919 to improve the lives of children through better education, health care, and economic opportunities, as well as providing emergency aid in natural disasters, war, and other conflicts.",
        logoURL: "https://silkroadtechnology.com/wp-content/uploads/2015/01/save_the_children_logo2.png",
        totalDonated: 0,
    },
    {
        name: "Black Lives Matter",
        link: "https://blacklivesmatter.com/",
        description: "Black Lives Matter is a decentralized movement in the United States advocating for non-violent civil disobedience in protest against incidents of police brutality and all racially motivated violence against African-American people.",
        logoURL: "https://ih1.redbubble.net/image.296010024.6499/flat,750x1000,075,f.jpg",
        totalDonated: 0,
    },
]